project:
  type: book
  output-dir: docs

book:
  title: "RIABIA + RLadies: Capacitación para la Docencia en Bioinformática"
  author: "Verónica Jimenez, Evelia Coss, Quetzally Medina, Ernestina Godoy, Nelly Sélem, Sofía Zorrilla"
  date: "09/21/2025"
  page-navigation: true
  chapters:
  - index.qmd
  - part: "**Sección 1** - Bienvenida e Introducción"
    chapters:
    - intro.qmd
    - Cap1.qmd
  - part: "**Sección 2** - Modelos mentales y carga Cognitiva"
    chapters:
    - Cap2A.qmd
  - part: "**Sección 3** - Memoria y otros principios"
    chapters:
    - Cap3A.qmd
  - part: "**Sección 4** - Enseñar en línea y Planificación de cursos"
    chapters:
    - Cap5A.qmd
    - Cap5B.qmd
  - part: "**Sección 5** - Audiencia y Simulación de entrenamiento"
    chapters:
    - Cap4A.qmd
    - Cap4B.qmd
  - part: "**Sección 6** - Programación en vivo y entrenamientos"
    chapters:
    - Cap6A.qmd
  # Information
  site-url: https://rladiesmx.netlify.app/ # 📍URL del sitio completo Rladies Mexico
  repo-url: https://github.com/EveliaCoss/RIABIA_RLadies_2026_Capacitacion_Docente # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "logos/Logo_Textoprincipal.png" # icono de la pagina en pestana

format:
  html:
    logo: "logos/Logo_Textoprincipal.png"
    toc-depth: 4
    number-depth: 3
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    freeze: false  # Desactivar congelamiento

editor: visual

