---
title: "Simulación de entrenamiento 1 (en grupos)"
date: "09/23/2025"
author:
    - name: Evelia Coss
      url: https://eveliacoss.github.io/ 
      orcid: https://orcid.org/0000-0002-7087-2977
      email: ecosnav@gmail.com
format:
  html:
    other-links:
      - text: Notas de la Capacitación
        href: https://docs.google.com/document/d/18cBrf20LvnqC8TXWCcJgz8unHtD2VN4UxXLGpF3yyzI/edit?usp=sharing 
---

::: {.callout-warning title="👩💻 Práctica de codificación en vivo" icon="false"}
- Formen grupos de tres personas.
- Asignen tres roles, que rotarán después de cada ronda:
  + 🎤 Presentador(a)
  + ⏱️ Responsable del tiempo
  + 📝 Tomador(a) de notas
- Cada integrante tendrá 3 minutos para enseñar una parte de la lección elegida mediante codificación en vivo.
- Antes de comenzar, expliquen brevemente:
  + qué van a enseñar, y
  + qué conocimientos previos se supone que ya tiene la audiencia.
- Durante la demostración, los demás integrantes observarán sin programar al mismo tiempo.
- Al finalizar, dediquen aproximadamente 1 minuto por persona a compartir retroalimentación utilizando la rúbrica 2×2. Quien presentó debe comenzar con una breve autoevaluación.
- El/la responsable del tiempo se encargará de mantener la actividad dentro de los tiempos establecidos.
- El/la tomador(a) de notas registrará los principales comentarios de retroalimentación en el Etherpad.
- Cambien los roles y repitan la dinámica hasta que las tres personas hayan realizado la demostración.

**Duración total aproximada: 25 minutos.**
:::
